/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertemuan.pkg8;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Nashir
 */
public class EntryPanel extends javax.swing.JPanel {
    Mahasiswa _mahasiswa=null;
    JScrollPane mainScrollPane;
    /**
     * Creates new form EntryPanel
     */
    public EntryPanel(JScrollPane mainScrollPane) {
        this.mainScrollPane=mainScrollPane;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        namaLabel1 = new javax.swing.JLabel();
        namaLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        nimLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        nimTextField = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        genderLabel = new javax.swing.JLabel();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        tinggiLabel = new javax.swing.JLabel();
        tinggiBadanSpinner = new javax.swing.JSpinner();
        hobiLabel = new javax.swing.JLabel();
        makanCheckBox = new javax.swing.JCheckBox();
        tidurCheckBox = new javax.swing.JCheckBox();
        berenangCheckBox = new javax.swing.JCheckBox();
        provinsiComboBox = new javax.swing.JComboBox<>();
        provinsiLabel = new javax.swing.JLabel();
        editButtonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editButtonPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        keluarButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(36, 47, 65));

        namaLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        namaLabel1.setForeground(new java.awt.Color(204, 204, 204));
        namaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLabel1.setText("FORM ISIAN MAHASISWA");

        namaLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(204, 204, 204));
        namaLabel.setText("Nama");

        userNameTextField.setBackground(new java.awt.Color(36, 47, 65));
        userNameTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        userNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        userNameTextField.setBorder(null);
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        nimLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        nimLabel.setForeground(new java.awt.Color(204, 204, 204));
        nimLabel.setText("Nim");

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        nimTextField.setBackground(new java.awt.Color(36, 47, 65));
        nimTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nimTextField.setForeground(new java.awt.Color(255, 255, 255));
        nimTextField.setBorder(null);
        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        genderLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(204, 204, 204));
        genderLabel.setText("Jenis Kelamin");

        lakiRadioButton.setBackground(new java.awt.Color(36, 47, 65));
        lakiRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lakiRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        lakiRadioButton.setText("Laki-laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        perempuanRadioButton.setBackground(new java.awt.Color(36, 47, 65));
        perempuanRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        perempuanRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        tinggiLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        tinggiLabel.setForeground(new java.awt.Color(204, 204, 204));
        tinggiLabel.setText("Tinggi Badan");

        tinggiBadanSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 250.0d, 1.0d));

        hobiLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        hobiLabel.setForeground(new java.awt.Color(204, 204, 204));
        hobiLabel.setText("Hobi");

        makanCheckBox.setBackground(new java.awt.Color(36, 47, 65));
        makanCheckBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        makanCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        makanCheckBox.setText("Makan");
        makanCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makanCheckBoxActionPerformed(evt);
            }
        });

        tidurCheckBox.setBackground(new java.awt.Color(36, 47, 65));
        tidurCheckBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tidurCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        tidurCheckBox.setText("Tidur");

        berenangCheckBox.setBackground(new java.awt.Color(36, 47, 65));
        berenangCheckBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        berenangCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        berenangCheckBox.setText("Berenang");

        provinsiComboBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        provinsiComboBox.setForeground(new java.awt.Color(36, 47, 65));
        provinsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jawa Timur", "Jawa Barat", "Jawa Tengah", "DKI jakarta", "Madura", "DIY yogyakarta" }));
        provinsiComboBox.setBorder(null);

        provinsiLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        provinsiLabel.setForeground(new java.awt.Color(204, 204, 204));
        provinsiLabel.setText("Provinsi");

        editButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        editButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editButtonPanelMouseReleased(evt);
            }
        });
        editButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Edit");
        editButtonPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        editButtonPanel1.setBackground(new java.awt.Color(97, 212, 195));
        editButtonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButtonPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editButtonPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editButtonPanel1MouseReleased(evt);
            }
        });
        editButtonPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Simpan");
        editButtonPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        keluarButton.setText("Keluar");
        keluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarButtonActionPerformed(evt);
            }
        });

        viewButton.setText("Veiw");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(namaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaLabel)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(userNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(makanCheckBox)
                                            .addGap(18, 18, 18)
                                            .addComponent(tidurCheckBox)
                                            .addGap(18, 18, 18)
                                            .addComponent(berenangCheckBox))
                                        .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nimLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(lakiRadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(perempuanRadioButton))
                                        .addComponent(tinggiLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tinggiBadanSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(provinsiComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nimTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(hobiLabel)
                                    .addComponent(provinsiLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(editButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(124, 124, 124)
                                        .addComponent(editButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(keluarButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namaLabel)
                .addGap(13, 13, 13)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(genderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(12, 12, 12)
                .addComponent(tinggiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinggiBadanSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hobiLabel)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makanCheckBox)
                    .addComponent(tidurCheckBox)
                    .addComponent(berenangCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(provinsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(provinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(keluarButton)
                    .addComponent(viewButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void makanCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makanCheckBoxActionPerformed

    private void editButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMouseClicked
        // TODO add your handling code here:
        String nim = nimTextField.getText();
        try {
            _mahasiswa = Database.getInstance().getMhsByNim(nim);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        userNameTextField.setText(_mahasiswa.getNama());
        nimTextField.setText(_mahasiswa.getNim());
        if (_mahasiswa.getGender().equalsIgnoreCase("laki-laki")) {
            lakiRadioButton.setSelected(true);
        } else if (_mahasiswa.getGender().equalsIgnoreCase("perempuan")) {
            perempuanRadioButton.setSelected(true);
        }
        tinggiBadanSpinner.setValue(_mahasiswa.getTinggi());
        for (String hobi : _mahasiswa.getHobi()) {
            if (hobi.equalsIgnoreCase("makan")) {
                makanCheckBox.setSelected(true);
            } else if (hobi.equalsIgnoreCase("tidur")) {
                tidurCheckBox.setSelected(true);
            } else if (hobi.equalsIgnoreCase("berenang")) {
                berenangCheckBox.setSelected(true);
            } else {
                break;
            }
            //System.out.println(_mahasiswa.getHobi()[i]);
        }
        for (int i = 0; i < provinsiComboBox.getItemCount(); i++) {
            if (provinsiComboBox.getItemAt(i).equalsIgnoreCase(_mahasiswa.getProvAsal())) {
                provinsiComboBox.setSelectedIndex(i);
            }
        }
        System.out.println(Database.getInstance().getSize());
    }//GEN-LAST:event_editButtonPanelMouseClicked

    private void editButtonPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMouseEntered
        // TODO add your handling code here:
        editButtonPanel.setBackground(new Color(97, 225, 208));
    }//GEN-LAST:event_editButtonPanelMouseEntered

    private void editButtonPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMouseExited
        // TODO add your handling code here:
        editButtonPanel.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_editButtonPanelMouseExited

    private void editButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMousePressed
        // TODO add your handling code here:
        editButtonPanel.setBackground(new Color(97, 196, 199));
    }//GEN-LAST:event_editButtonPanelMousePressed

    private void editButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMouseReleased
        // TODO add your handling code here:
        editButtonPanel.setBackground(new Color(97, 225, 208));
    }//GEN-LAST:event_editButtonPanelMouseReleased

    private void editButtonPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MouseClicked
        // TODO add your handling code here:
        String nama = userNameTextField.getText();
        String nim = nimTextField.getText();
        String gender = "";
        if (lakiRadioButton.isSelected()) {
            gender = "laki-laki";
        } else if (perempuanRadioButton.isSelected()) {
            gender = "perempuan";
        }
        double tinggi = Double.parseDouble(tinggiBadanSpinner.getValue().toString());
        ArrayList<String> hobi = new ArrayList<>();

        if (makanCheckBox.isSelected()) {
            hobi.add("makan");
        }
        if (tidurCheckBox.isSelected()) {
            hobi.add("tidur");
        }
        if (berenangCheckBox.isSelected()) {
            hobi.add("berenang");
        }
        String provinsi = provinsiComboBox.getSelectedItem().toString();
        if (_mahasiswa != null) {
            Database.getInstance().setMahasiswa(Database.getInstance().getIndexMhsByNim(_mahasiswa.getNim()), _mahasiswa);
            _mahasiswa = null;
        } else {
            Mahasiswa mhs;
            try {
                mhs = new Mahasiswa(nama,nim,gender,tinggi,hobi,provinsi);
                try {
                    Database.getInstance().addMahasiswa(mhs);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    return;
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
        }
        userNameTextField.setText("");
        nimTextField.setText("");
        makanCheckBox.setSelected(false);
        tidurCheckBox.setSelected(false);
        berenangCheckBox.setSelected(false);
        provinsiComboBox.setSelectedIndex(0);
//        buttonGroup1.clearSelection();
        tinggiBadanSpinner.setValue(0);
        JOptionPane.showMessageDialog(this, "Pengyimpanan Data Berhasil!!");
    }//GEN-LAST:event_editButtonPanel1MouseClicked

    private void editButtonPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MouseEntered
        // TODO add your handling code here:
        editButtonPanel1.setBackground(new Color(97, 225, 208));
    }//GEN-LAST:event_editButtonPanel1MouseEntered

    private void editButtonPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MouseExited
        // TODO add your handling code here:
        editButtonPanel1.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_editButtonPanel1MouseExited

    private void editButtonPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MousePressed
        // TODO add your handling code here:
        editButtonPanel1.setBackground(new Color(97, 196, 199));
    }//GEN-LAST:event_editButtonPanel1MousePressed

    private void editButtonPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MouseReleased
        // TODO add your handling code here:
        editButtonPanel1.setBackground(new Color(97, 225, 208));
    }//GEN-LAST:event_editButtonPanel1MouseReleased

    private void keluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarButtonActionPerformed
        // TODO add your handling code here:
        mainScrollPane.setViewportView(new LoginPanel(mainScrollPane));
    }//GEN-LAST:event_keluarButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        mainScrollPane.setViewportView(new ViewMahasiswaPanel());
    }//GEN-LAST:event_viewButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox berenangCheckBox;
    private javax.swing.JPanel editButtonPanel;
    private javax.swing.JPanel editButtonPanel1;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hobiLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton keluarButton;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JCheckBox makanCheckBox;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaLabel1;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> provinsiComboBox;
    private javax.swing.JLabel provinsiLabel;
    private javax.swing.JCheckBox tidurCheckBox;
    private javax.swing.JSpinner tinggiBadanSpinner;
    private javax.swing.JLabel tinggiLabel;
    private javax.swing.JTextField userNameTextField;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
