/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertemuan.pkg8;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nashir
 */
public class FormData extends javax.swing.JFrame {

    private Mahasiswa _mahasiswa = null;

    /**
     * Creates new form FormData
     */
    public FormData() {
        initComponents();
        mainScrollPane.setViewportView(new LoginPanel(mainScrollPane));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        loginPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        unameTextField = new javax.swing.JTextField();
        passwordTextField = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        editButtonPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        entryPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        namaLabel5 = new javax.swing.JLabel();
        namaLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        namaLabel = new javax.swing.JLabel();
        nimLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        tinggiLabel = new javax.swing.JLabel();
        hobiLabel = new javax.swing.JLabel();
        provinsiLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        nimTextField = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        tinggiBadanSpinner = new javax.swing.JSpinner();
        makanCheckBox = new javax.swing.JCheckBox();
        tidurCheckBox = new javax.swing.JCheckBox();
        berenangCheckBox = new javax.swing.JCheckBox();
        provinsiComboBox = new javax.swing.JComboBox<>();
        editButtonPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        editButtonPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        namaLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        mainScrollPane = new javax.swing.JScrollPane();

        loginPanel.setBackground(new java.awt.Color(97, 212, 195));
        loginPanel.setMaximumSize(new java.awt.Dimension(636, 452));
        loginPanel.setMinimumSize(new java.awt.Dimension(636, 452));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setText("Password:");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setText("Username:");

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));

        unameTextField.setBackground(new java.awt.Color(97, 212, 195));
        unameTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        unameTextField.setBorder(null);
        unameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameTextFieldActionPerformed(evt);
            }
        });

        passwordTextField.setBackground(new java.awt.Color(97, 212, 195));
        passwordTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        passwordTextField.setBorder(null);
        passwordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTextFieldActionPerformed(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));

        editButtonPanel2.setBackground(new java.awt.Color(0, 153, 153));
        editButtonPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButtonPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonPanel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonPanel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonPanel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editButtonPanel2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editButtonPanel2MouseReleased(evt);
            }
        });
        editButtonPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Masuk");
        editButtonPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator6)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                            .addComponent(unameTextField))))
                .addContainerGap(122, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editButtonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(173, 173, 173))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(50, 50, 50))
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addComponent(unameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)))
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(loginPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addComponent(editButtonPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
        );

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));

        namaLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        namaLabel5.setForeground(new java.awt.Color(255, 255, 255));
        namaLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nashir\\Downloads\\ic_github_face_black_48dp.png")); // NOI18N

        namaLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        namaLabel2.setText("Author: Nashir Wahyudi");

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));

        namaLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        namaLabel.setForeground(new java.awt.Color(204, 204, 204));
        namaLabel.setText("Nama");

        nimLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        nimLabel.setForeground(new java.awt.Color(204, 204, 204));
        nimLabel.setText("Nim");

        genderLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        genderLabel.setForeground(new java.awt.Color(204, 204, 204));
        genderLabel.setText("Jenis Kelamin");

        tinggiLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        tinggiLabel.setForeground(new java.awt.Color(204, 204, 204));
        tinggiLabel.setText("Tinggi Badan");

        hobiLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        hobiLabel.setForeground(new java.awt.Color(204, 204, 204));
        hobiLabel.setText("Hobi");

        provinsiLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        provinsiLabel.setForeground(new java.awt.Color(204, 204, 204));
        provinsiLabel.setText("Provinsi");

        userNameTextField.setBackground(new java.awt.Color(36, 47, 65));
        userNameTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        userNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        userNameTextField.setBorder(null);
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });

        nimTextField.setBackground(new java.awt.Color(36, 47, 65));
        nimTextField.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        nimTextField.setForeground(new java.awt.Color(255, 255, 255));
        nimTextField.setBorder(null);
        nimTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimTextFieldActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(204, 204, 204));

        jSeparator3.setForeground(new java.awt.Color(204, 204, 204));

        lakiRadioButton.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(lakiRadioButton);
        lakiRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lakiRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        lakiRadioButton.setText("Laki-laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        perempuanRadioButton.setBackground(new java.awt.Color(36, 47, 65));
        buttonGroup1.add(perempuanRadioButton);
        perempuanRadioButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        perempuanRadioButton.setForeground(new java.awt.Color(204, 204, 204));
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        tinggiBadanSpinner.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 250.0d, 1.0d));

        makanCheckBox.setBackground(new java.awt.Color(36, 47, 65));
        makanCheckBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        makanCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        makanCheckBox.setText("Makan");
        makanCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makanCheckBoxActionPerformed(evt);
            }
        });

        tidurCheckBox.setBackground(new java.awt.Color(36, 47, 65));
        tidurCheckBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tidurCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        tidurCheckBox.setText("Tidur");

        berenangCheckBox.setBackground(new java.awt.Color(36, 47, 65));
        berenangCheckBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        berenangCheckBox.setForeground(new java.awt.Color(204, 204, 204));
        berenangCheckBox.setText("Berenang");

        provinsiComboBox.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        provinsiComboBox.setForeground(new java.awt.Color(36, 47, 65));
        provinsiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jawa Timur", "Jawa Barat", "Jawa Tengah", "DKI jakarta", "Madura", "DIY yogyakarta" }));
        provinsiComboBox.setBorder(null);

        editButtonPanel.setBackground(new java.awt.Color(97, 212, 195));
        editButtonPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButtonPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonPanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonPanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonPanelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editButtonPanelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editButtonPanelMouseReleased(evt);
            }
        });
        editButtonPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Edit");
        editButtonPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        editButtonPanel1.setBackground(new java.awt.Color(97, 212, 195));
        editButtonPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButtonPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonPanel1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editButtonPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                editButtonPanel1MouseReleased(evt);
            }
        });
        editButtonPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setText("Simpan");
        editButtonPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        namaLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        namaLabel1.setForeground(new java.awt.Color(204, 204, 204));
        namaLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaLabel1.setText("FORM ISIAN MAHASISWA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(namaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaLabel)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(userNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(makanCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(tidurCheckBox)
                                    .addGap(18, 18, 18)
                                    .addComponent(berenangCheckBox))
                                .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nimLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(lakiRadioButton)
                                    .addGap(18, 18, 18)
                                    .addComponent(perempuanRadioButton))
                                .addComponent(tinggiLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(tinggiBadanSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(provinsiComboBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nimTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(hobiLabel)
                            .addComponent(provinsiLabel)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(editButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(124, 124, 124)
                                .addComponent(editButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(412, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(namaLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namaLabel)
                .addGap(13, 13, 13)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nimTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(genderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addGap(12, 12, 12)
                .addComponent(tinggiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tinggiBadanSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hobiLabel)
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(makanCheckBox)
                    .addComponent(tidurCheckBox)
                    .addComponent(berenangCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(provinsiLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(provinsiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(editButtonPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editButtonPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(namaLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(namaLabel5)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(namaLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(768, 768, 768))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(namaLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout entryPanelLayout = new javax.swing.GroupLayout(entryPanel);
        entryPanel.setLayout(entryPanelLayout);
        entryPanelLayout.setHorizontalGroup(
            entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryPanelLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 805, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1055, Short.MAX_VALUE))
        );
        entryPanelLayout.setVerticalGroup(
            entryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entryPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 1486, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Data Mahasiswa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 735, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void unameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameTextFieldActionPerformed

    private void passwordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTextFieldActionPerformed

    private void editButtonPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel2MouseClicked
        // TODO add your handling code here:
        mainScrollPane.setViewportView(entryPanel);
        
    }//GEN-LAST:event_editButtonPanel2MouseClicked

    private void editButtonPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonPanel2MouseEntered

    private void editButtonPanel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonPanel2MouseExited

    private void editButtonPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonPanel2MousePressed

    private void editButtonPanel2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_editButtonPanel2MouseReleased

    private void editButtonPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MouseReleased
        // TODO add your handling code here:
        editButtonPanel1.setBackground(new Color(97, 225, 208));
    }//GEN-LAST:event_editButtonPanel1MouseReleased

    private void editButtonPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MousePressed
        // TODO add your handling code here:
        editButtonPanel1.setBackground(new Color(97, 196, 199));
    }//GEN-LAST:event_editButtonPanel1MousePressed

    private void editButtonPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MouseExited
        // TODO add your handling code here:
        editButtonPanel1.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_editButtonPanel1MouseExited

    private void editButtonPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MouseEntered
        // TODO add your handling code here:
        editButtonPanel1.setBackground(new Color(97, 225, 208));
    }//GEN-LAST:event_editButtonPanel1MouseEntered

    private void editButtonPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanel1MouseClicked
        // TODO add your handling code here:
        String nama = userNameTextField.getText();
        String nim = nimTextField.getText();
        String gender = "";
        if (lakiRadioButton.isSelected()) {
            gender = "laki-laki";
        } else if (perempuanRadioButton.isSelected()) {
            gender = "perempuan";
        }
        double tinggi = Double.parseDouble(tinggiBadanSpinner.getValue().toString());
        ArrayList<String> hobi = new ArrayList<>();

        if (makanCheckBox.isSelected()) {
            hobi.add("makan");
        }
        if (tidurCheckBox.isSelected()) {
            hobi.add("tidur");
        }
        if (berenangCheckBox.isSelected()) {
            hobi.add("berenang");
        }
        String provinsi = provinsiComboBox.getSelectedItem().toString();
        if (_mahasiswa != null) {
            Database.getInstance().setMahasiswa(Database.getInstance().getIndexMhsByNim(_mahasiswa.getNim()), _mahasiswa);
            _mahasiswa = null;
        } else {
            Mahasiswa mhs;
            try {
                mhs = new Mahasiswa(nama,nim,gender,tinggi,hobi,provinsi);
                try {
                    Database.getInstance().addMahasiswa(mhs);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, ex.getMessage());
                    return;
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
                return;
            }
        }
        userNameTextField.setText("");
        nimTextField.setText("");
        makanCheckBox.setSelected(false);
        tidurCheckBox.setSelected(false);
        berenangCheckBox.setSelected(false);
        provinsiComboBox.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        tinggiBadanSpinner.setValue(0);
        JOptionPane.showMessageDialog(this, "Pengyimpanan Data Berhasil!!");
    }//GEN-LAST:event_editButtonPanel1MouseClicked

    private void editButtonPanelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMouseReleased
        // TODO add your handling code here:
        editButtonPanel.setBackground(new Color(97, 225, 208));
    }//GEN-LAST:event_editButtonPanelMouseReleased

    private void editButtonPanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMousePressed
        // TODO add your handling code here:
        editButtonPanel.setBackground(new Color(97, 196, 199));
    }//GEN-LAST:event_editButtonPanelMousePressed

    private void editButtonPanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMouseExited
        // TODO add your handling code here:
        editButtonPanel.setBackground(new Color(97, 212, 195));
    }//GEN-LAST:event_editButtonPanelMouseExited

    private void editButtonPanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMouseEntered
        // TODO add your handling code here:
        editButtonPanel.setBackground(new Color(97, 225, 208));
    }//GEN-LAST:event_editButtonPanelMouseEntered

    private void editButtonPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonPanelMouseClicked
        // TODO add your handling code here:
        String nim = nimTextField.getText();
        try {
            _mahasiswa = Database.getInstance().getMhsByNim(nim);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
            return;
        }
        userNameTextField.setText(_mahasiswa.getNama());
        nimTextField.setText(_mahasiswa.getNim());
        if (_mahasiswa.getGender().equalsIgnoreCase("laki-laki")) {
            lakiRadioButton.setSelected(true);
        } else if (_mahasiswa.getGender().equalsIgnoreCase("perempuan")) {
            perempuanRadioButton.setSelected(true);
        }
        tinggiBadanSpinner.setValue(_mahasiswa.getTinggi());
        for (String hobi : _mahasiswa.getHobi()) {
            if (hobi.equalsIgnoreCase("makan")) {
                makanCheckBox.setSelected(true);
            } else if (hobi.equalsIgnoreCase("tidur")) {
                tidurCheckBox.setSelected(true);
            } else if (hobi.equalsIgnoreCase("berenang")) {
                berenangCheckBox.setSelected(true);
            } else {
                break;
            }
            //System.out.println(_mahasiswa.getHobi()[i]);
        }
        for (int i = 0; i < provinsiComboBox.getItemCount(); i++) {
            if (provinsiComboBox.getItemAt(i).equalsIgnoreCase(_mahasiswa.getProvAsal())) {
                provinsiComboBox.setSelectedIndex(i);
            }
        }
        System.out.println(Database.getInstance().getSize());
    }//GEN-LAST:event_editButtonPanelMouseClicked

    private void makanCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makanCheckBoxActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void nimTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimTextFieldActionPerformed

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                try{
//                    Thread.sleep(7000);
//                }catch(Exception e){
//                    
//                }
               
                new FormData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox berenangCheckBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel editButtonPanel;
    private javax.swing.JPanel editButtonPanel1;
    private javax.swing.JPanel editButtonPanel2;
    private javax.swing.JPanel entryPanel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel hobiLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JScrollPane mainScrollPane;
    private javax.swing.JCheckBox makanCheckBox;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JLabel namaLabel1;
    private javax.swing.JLabel namaLabel2;
    private javax.swing.JLabel namaLabel5;
    private javax.swing.JLabel nimLabel;
    private javax.swing.JTextField nimTextField;
    private javax.swing.JTextField passwordTextField;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JComboBox<String> provinsiComboBox;
    private javax.swing.JLabel provinsiLabel;
    private javax.swing.JCheckBox tidurCheckBox;
    private javax.swing.JSpinner tinggiBadanSpinner;
    private javax.swing.JLabel tinggiLabel;
    private javax.swing.JTextField unameTextField;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
