/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pertemuan.pkg8;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nashir
 */
public class ViewMahasiswaPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewMahasiswaPanel
     */
    public ViewMahasiswaPanel() {
        initComponents();
        DefaultTableModel dm = (DefaultTableModel) viewMahasiswaTable.getModel();
        ArrayList<Mahasiswa> temp = Database.getInstance().getAllMhs();
        for (int i = 0; i < temp.size(); i++) {
            Object rowData[] = {Database.getInstance().getMahasiswaByIndex(i).getNim(), Database.getInstance().getMahasiswaByIndex(i).getNama(),
                Database.getInstance().getMahasiswaByIndex(i).getGender(), Database.getInstance().getMahasiswaByIndex(i).getProvAsal()};
            dm.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        viewMahasiswaTable = new javax.swing.JTable();

        viewMahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NIM", "Nama", "Gender", "Provinsi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewMahasiswaTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewMahasiswaTable;
    // End of variables declaration//GEN-END:variables
}
